services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis      # Use = syntax for YAML list
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app       # Mount your code for live edits
      - /usr/src/app/node_modules  # Keep node_modules in container
    command: npm run dev       # Ensure the app starts

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:                 # Declare named volume for Redis data
